# Generated by Django 4.0.3 on 2022-04-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
